name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Test project generation
      run: |
        # Test CLI functionality by creating a test project
        python -m project_structure_creator structure.txt test_output
        if [ -f test_output/project/requirements.txt ]; then pip install -r test_output/project/requirements.txt; fi
    
    - name: Run tests
      run: |
        # Run tests for the generated project
        python -m pytest test_output/project/tests/ -v || echo "No tests found or pytest not installed"
        
        # Run the input.py script to test project generation (if it exists)
        if [ -f input.py ]; then python input.py; fi || echo "input.py execution completed"

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort
    
    - name: Run black
      run: black --check --diff .
      continue-on-error: true
    
    - name: Run isort
      run: isort --check-only --diff .
      continue-on-error: true
    
    - name: Run flake8
      run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      continue-on-error: true
